### ISSUE TITLE
Update build environments to latest Python version

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftjs_exporter#69]
At the moment the project is tested on Python 2.7, 3.4, 3.5. We need to update this to test Python 3.6 (or whatever the latest version is when we get to this task).

Also, I'm very keen on limiting the number of environments we test on. Would it be reasonable to:

- Only build on Python 2.7, and the oldest supported Python 3 version (3.4) and the latest, not all intermediary versions?
- Only build on Python 2.7, and the latest Python 3 version?

**Comment by thibaudcolas** [comment]
Assigning to @loicteixeira to look at based on our conversation in https://github.com/springload/wagtaildraftail/pull/59 🙂

**Comment by loicteixeira** [comment]
As discussed offline, I'll port over the work which has been done on `wagtaildraftail`, however because this project doesn't depends on Django or Wagtail, this comes down to Python.

So regarding which versions to test, I reckon the minimum `3.x` version should be `3.4` (like `wagtaildraftail` and almost everybody else). So we would support `2.7`, `3.4`, `3.5`, `3.6`. Given the build time is 1 to 3 minutes per version, I don't see a reason to skip one.
