### ISSUE TITLE
Remove support for class based decorator

### ISSUE THREAD

**Issue by loicteixeira** [springload/draftjs_exporter#73]
Capturing offline discussions for a public discussion.

Currently a decorator can be written as a `function` (accepting a single positional argument `props`) or a `class` (with a single `render` method accepting a single positional argument `props`) which has a few issues:
- Nothing is passed to the `__init__` of the `class` but instead everything is passed to `props` which makes the `class` quite useless. Moving the props to the `__init__` will either create  boilerplate or will force the user to inherit from a custom class which does that for them. In short, it's not clear which benefit there is to use a class.
- To keep naming consistent, functions are names are camel cased (so when you update your config file, you don't have to think whether it's a function or a class) which gets the linter to complain. The library should not encourage non-PEP8 compliant code.

We were therefore thinking of removing support for class based decorators. Any thoughts?

**Comment by loicteixeira** [comment]
Pinging @everyonesdesign @su27 as you guys seem to have used the project a fair bit.

**Comment by everyonesdesign** [comment]
Yes, it's a long time since I worked with code using `draftjs_exporter`, but I remember I thought about that.

I didn't have any cases for classes usage here, and I could do everything I've done with functions components.

So, if there're no known cases for classes usage here, I think it's a good idea to drop them and use functions. It's a win for code readability.

**Comment by thibaudcolas** [comment]
Thanks everyone for the feedback 😊 

Initially I used classes because this project started as a port of a Ruby exporter, which [uses classes](https://github.com/ignitionworks/draftjs_exporter/blob/master/lib/draftjs_exporter/entities/link.rb). Then I tried to align with "what React does", but realised classes weren't actually necessary. They do have the advantage of allowing some sort of configuration of the decorators:

https://github.com/springload/draftjs_exporter/blob/c963514cf0d81261677376d4323655e9efbb88cd/example.py#L53-L66

... but this can also be implemented with function composition (although that's not really a Python idiom).

----

The "cost of supporting classes" is:

https://github.com/springload/draftjs_exporter/blob/c963514cf0d81261677376d4323655e9efbb88cd/draftjs_exporter/dom.py#L79-L89

I don't know if there is much of a performance cost in this reflection code (would be easier to figure out once we tackled #65). Regardless, **I don't think we will remove support for classes any time soon**, but if we agree there isn't much of a point for them we'll update the documentation and example(s) to use functions defined in snake_case (then people can name them however they want in their own project), or also use classes.

If we do remove support altogether, it would be a 2.0.0 release, and presumably we would want to group together other breaking changes, but we want this project to be as stable and boring as possible so we'll see when we get there.

**Comment by loicteixeira** [comment]
I don't think the performance cost of supporting classes is that high (but proper numbers would be good).

However we can already see it won't work with the `Link` class example because then, it would need to pass the right parameters to the constructor depending on what the class' `__init__` accepts (unless it has `**kwargs` so the signature is always the same, but then you have to somehow have the `props` on one side and some additional `kwargs` on the other hand).

I can agree with leaving it off until the `2.0.0` release (I had forgotten we reached `1.0` already), maybe by then we will have a better idea whether classes are useful. In the meantime, updating the documentation is a good idea.

Thanks for the feedback everyone.

**Comment by thibaudcolas** [comment]
I just realised while thinking about version 2 that class decorators are the only way to define composite decorators (for arbitrary text replacement).

I imagine these could be turned into dicts, following what Draft.js does (https://draftjs.org/docs/advanced-topics-decorators.html#compositedecorator), a pattern somewhat similar to that of the block definitions:

```js
{
    // A function in Draft.js (using a regex or anything else) – could just be the regex for the exporter.
    strategy: hashtagStrategy,
    // A React component in Draft.js – Python function in our case.
    // Should be called `element` if we followed the same pattern as the block deifinitions and also supported using tags directly.
    component: HashtagSpan,
},
```

This is a bit more work than just removing those conditionals in `DOM.render`.

Oh and in terms of performance, the gain seems to be 2-6% from early testing using the new benchmark (literally every block, style, entity, piece of text goes through these conditionals, and the checks are ordered from least to most common).
