### ISSUE TITLE
Missing git tags for 2.1.1

### ISSUE THREAD

**Issue by kryskool** [springload/draftjs_exporter#97]
Hi

The git tag 2.1.1 is missing for this commit 220f2b93f2fd39329077058114616314fe495c81

Please add it

Regards,

**Comment by thibaudcolas** [comment]
Hey @kryskool, nice catch. I missed that last step when doing the last release – here's the tag: https://github.com/springload/draftjs_exporter/tree/v2.1.1.

I'll see in the future if there is a way to automate this, because the less frequently we do releases the more likely we are to miss some of the manual steps.

**Comment by kryskool** [comment]
Hi @thibaudcolas 

For the future, maybe use [setuptools_scm](https://github.com/pypa/setuptools_scm) and version number for sdist, wheel is automaticaly taken from git

Regards,
